"""Mock Copilot CLI smoke — T2.4.

Verifies that:
  - tools/mock_ai_cli installed as `copilot` binary tolerates the argv
    generated by CopilotProvider.build_argv (TUI-safe flags + intro).
  - The bundled `tests/scenarios/copilot_basic.json` matches the
    canonical mock_ai_cli scenario schema and produces the expected
    replies on stdin → stdout.
  - find_binary() resolves a binary placed on $PATH (via shutil.which),
    not just the explicit search_paths list.

These tests don't spawn under VTE — they pipe stdin/stdout directly so
the assertion focuses on argv compatibility + scenario parsing rather
than TUI rendering. T2.10 covers the full VTE-on-mock E2E.
"""
from __future__ import annotations

import json
import os
import shutil
import stat
import subprocess
from pathlib import Path

import pytest

from bterminal.providers import load_providers_config
from bterminal.providers.copilot import CopilotProvider

REPO_ROOT = Path(__file__).parent.parent
MOCK_SRC = REPO_ROOT / "tools" / "mock_ai_cli"
SCENARIO_PATH = REPO_ROOT / "tests" / "scenarios" / "copilot_basic.json"


@pytest.fixture
def fake_copilot_binary(tmp_path):
    """Copy tools/mock_ai_cli into tmp_path/copilot and mark executable."""
    fake = tmp_path / "copilot"
    shutil.copy(str(MOCK_SRC), str(fake))
    fake.chmod(fake.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return fake


@pytest.fixture
def copilot_provider(fake_copilot_binary):
    """CopilotProvider whose find_binary() resolves to the fake."""
    cfg = json.loads(json.dumps(load_providers_config()["providers"]["copilot"]))
    cfg["binary"]["search_paths"] = [str(fake_copilot_binary)]
    return CopilotProvider(cfg)


# ─── Scenario file sanity ────────────────────────────────────────────────────

def test_scenario_file_exists():
    assert SCENARIO_PATH.exists()


def test_scenario_is_valid_json_with_expected_keys():
    data = json.loads(SCENARIO_PATH.read_text())
    assert "responses" in data
    assert "default_reply" in data
    # Sanity — each response has trigger + reply
    for rule in data["responses"]:
        assert "trigger" in rule
        assert "reply" in rule


def test_scenario_default_reply_uses_copilot_prompt_prefix():
    """Copilot-styled `> {input}` echo for unmatched lines."""
    data = json.loads(SCENARIO_PATH.read_text())
    assert data["default_reply"].startswith(">")


# ─── Mock binary tolerates Copilot argv ──────────────────────────────────────

def test_mock_runs_with_copilot_argv(copilot_provider, fake_copilot_binary):
    """Subprocess spawn with the EXACT argv CopilotProvider.build_argv
    generates — mock must not crash on unknown flags. We pipe stdin
    `/exit` so the process terminates cleanly within the timeout."""
    argv = copilot_provider.build_argv({}, "")
    # First entry is the binary path (resolved by find_binary)
    assert argv[0] == str(fake_copilot_binary)
    # TUI-safe flags must be present (--no-banner removed 2026-05-07
    # — real copilot v1.0.43 uses opt-in `--banner`, not `--no-banner`)
    assert "--no-mouse" in argv
    assert "--plain-diff" in argv
    assert "--no-color" in argv

    env = {**os.environ, "MOCK_AI_CLI_SCENARIO": str(SCENARIO_PATH)}
    proc = subprocess.Popen(
        argv,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env=env,
        text=True,
    )
    stdout, _stderr = proc.communicate(input="/exit\n", timeout=10)
    assert proc.returncode == 0


def test_mock_responds_to_hello(copilot_provider, fake_copilot_binary):
    """Mock honours the `hello` trigger from copilot_basic.json."""
    argv = copilot_provider.build_argv({}, "")
    env = {**os.environ, "MOCK_AI_CLI_SCENARIO": str(SCENARIO_PATH)}
    proc = subprocess.Popen(
        argv, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
        stderr=subprocess.PIPE, env=env, text=True,
    )
    stdout, _ = proc.communicate(input="hello\n/exit\n", timeout=10)
    assert "Copilot CLI ready" in stdout
    assert proc.returncode == 0


def test_mock_default_reply_uses_prompt_prefix(copilot_provider):
    """Unmatched input → '> {input}' default echo."""
    argv = copilot_provider.build_argv({}, "")
    env = {**os.environ, "MOCK_AI_CLI_SCENARIO": str(SCENARIO_PATH)}
    proc = subprocess.Popen(
        argv, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
        stderr=subprocess.PIPE, env=env, text=True,
    )
    stdout, _ = proc.communicate(input="some random text\n/exit\n", timeout=10)
    # `> some random text` is rendered for the default echo
    assert "> some random text" in stdout


def test_mock_with_resume_argv_still_works(copilot_provider):
    """Even with full provider_options (resume + yolo + model + add-dir
    + json_output + intro), the mock runs cleanly — verifies the whole
    argv shape is tolerable."""
    argv = copilot_provider.build_argv(
        {
            "project_dir": "/tmp/mock-project",
            "provider_options": {
                "resume": True,
                "skip_permissions": True,
                "model": "claude-sonnet-4-5",
                "json_output": True,
            },
        },
        "Test intro from BTerminal",
    )
    env = {**os.environ, "MOCK_AI_CLI_SCENARIO": str(SCENARIO_PATH)}
    proc = subprocess.Popen(
        argv, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
        stderr=subprocess.PIPE, env=env, text=True,
    )
    stdout, _ = proc.communicate(input="ping\n/exit\n", timeout=10)
    assert "pong" in stdout
    assert proc.returncode == 0


# ─── PATH-based binary discovery ─────────────────────────────────────────────

def test_find_binary_via_path_search(tmp_path, monkeypatch, fake_copilot_binary):
    """When explicit search_paths come up empty, find_binary() falls
    back to shutil.which on $PATH. Place the fake binary in tmp_path
    and add tmp_path to PATH — find_binary must resolve it."""
    cfg = json.loads(json.dumps(load_providers_config()["providers"]["copilot"]))
    cfg["binary"]["search_paths"] = []  # force PATH fallback

    monkeypatch.setenv(
        "PATH",
        f"{tmp_path}{os.pathsep}{os.environ.get('PATH', '')}",
    )
    p = CopilotProvider(cfg)
    found = p.find_binary()
    assert found == str(fake_copilot_binary)


def test_find_binary_returns_none_when_path_clean(tmp_path, monkeypatch):
    """If neither search_paths nor PATH contains a copilot binary,
    find_binary() returns None — signal to spawn_ai_cli to render the
    'binary not found' error script."""
    cfg = json.loads(json.dumps(load_providers_config()["providers"]["copilot"]))
    cfg["binary"]["search_paths"] = [str(tmp_path / "nope")]
    # Strip PATH entirely (also block shutil.which fallback)
    monkeypatch.setenv("PATH", "")
    monkeypatch.setattr("bterminal.providers.copilot.shutil.which",
                        lambda *a, **kw: None)
    p = CopilotProvider(cfg)
    assert p.find_binary() is None
