"""Single source of truth for rules_config defaults (BUG#28).

Three callsites needed to agree on these values:
  * bterminal.ui.panels.memory  — spinner init + fallback when DB
    has no row for the current project
  * bterminal.ui.terminal_tab._maybe_inject_rules — runtime fallback
    when the DB read raises
  * tools/ctx CLI — fallback in _rules_inject when rules_config has
    no row. The CLI also mirrors these via its own module-level
    constants (it's a standalone script that can't always import the
    package), so tests/test_ctx_defaults_consistency.py pins both
    sides to the same number.

Drift between any two of those callsites is a user-visible bug:
Memory panel claims "every 100 prompts" while the intro prompt
header (generated by tools/ctx) says "every 20 prompts".

This module is intentionally dependency-free (no Gtk, no sqlite)
so the CLI tools can `from bterminal.providers.ctx_defaults
import DEFAULT_INJECT_EVERY` without dragging in the world.
"""

DEFAULT_INJECT_EVERY = 100
DEFAULT_REFRESH_EVERY = 200

__all__ = ["DEFAULT_INJECT_EVERY", "DEFAULT_REFRESH_EVERY"]
